# Generated by Django 5.1.5 on 2025-01-27 09:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sessionapikey_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionapikey',
            name='api_key',
        ),
        migrations.AddField(
            model_name='sessionapikey',
            name='actual_key',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
