# Generated by Django 5.1.5 on 2025-01-27 10:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_alter_sessionapikey_options_sessionapikey_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sessionapikey",
            name="actual_key",
        ),
    ]
