# Generated by Django 5.1.5 on 2025-01-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_remove_sessionapikey_actual_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionapikey",
            name="key",
            field=models.CharField(default="a", max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
