# Generated by Django 5.1.5 on 2025-01-27 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_alter_sessionapikey_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sessionapikey",
            name="key",
        ),
    ]
